method: grid
metric:
  goal: minimize
  name: "val/loss"
parameters:
  epoch:
    values: [1]
  hidden_layer_shape:
    values: [[512], [256], [128]]
  learning_rate:
    values: [0.0001, 0.00001, 0.000001]
  minibatch_size:
    values: [1]
  optimizer:
    values: ["sgd", "adam"]
