method: random
metric:
  goal: minimize
  name: loss
parameters:
  epoch:
    values: [10, 25, 50]
  hidden_layer_shape:
    values: [[1024], [512], [256], [128]]
  learning_rate:
    values: [0.0001, 0.00001]
  minibatch_size:
    values: [32, 64, 128]
  optimizer:
    values: ["sgd", "adam"]
