method: random
metric:
  goal: minimize
  name: loss
parameters:
  epoch:
    values: [1, 5, 10, 25, 50]
  hidden_layer_shape:
    values: [[512], [256], [128], [512, 256], [512, 128], [256, 128], [512, 256, 128]]
  learning_rate:
    distribution: uniform
    max: 0.1
    min: 0
  minibatch_size:
    distribution: q_log_uniform_values
    max: 256
    min: 32
    q: 8
  optimizer:
    values: ["sgd", "adam"]
