run_name: "baseline"
seed: 43

# You need to provide models in ascending order by parameter count for MESS+ to work correctly.
model_zoo:
  meta-llama/Llama-3.2-1B-Instruct:
    category: "small"
    gpu_indices: [0]
    max_seq_len: 2048
    gpu_memory_utilization: 0.3
    quantization: null
  unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit:
    category: "medium"
    gpu_indices: [0]
    max_seq_len: 2048
    gpu_memory_utilization: 0.35
    quantization: "bitsandbytes"
  meta-llama/Llama-3.3-70B-Instruct:
    category: "large"
    gpu_indices: [1]
    max_seq_len: 2048
    gpu_memory_utilization: 0.9
    quantization: null

classifier_model:
  model_id: "answerdotai/ModernBERT-base"
  epochs: 1
  learning_rate: 0.00002
  weight_decay: 0.01
  batch_size: 16  # This only has an effect when memory dataset is activated
  max_length: 128
  warmup_ratio: 0.1
  threshold: 0.5
  dropout_rate: 0.1
  freeze_bert_layers: true
  memory_size: 0
  memory_strategy: random # This only works when memory_size > 0
  reset_optimizer: false
  regularization_lambda: 0.0
  gpu_index: 0
  disable_tqdm: false
  checkpoint_path: "classifier/checkpoints/mess_classifier_best_ckpt.pt"  # Path starts from the project root path.
  use_pretrained_classifier: true
  scoring_method: raw
  generate_training_dataset: true
  write_training_dataset_to_disk: true

algorithm:
  alpha: 0.75
  c: 1
  V: 0.01

lm_eval:
  # The run name will be the first benchmark in the list below.
  benchmarks: ["winogrande"]
  num_repeats: 1
  limit_num_samples: null
  # TODO: Make sure we disable eager mode for the actual experiments to be as energy efficient as possible.
  enforce_eager: true
  write_to_disk: false
