method: grid
metric:
  goal: minimize
  name: "val/loss"
parameters:
  epoch:
    values: [10, 25]
  hidden_layer_shape:
    values: [[512], [256], [128], [512, 256]]
  learning_rate:
    values: [0.001, 0.0001, 0.00001]
  minibatch_size:
    values: [32, 64]
  optimizer:
    values: ["sgd", "adam"]
